core/urls.py
from django.urls import path
from .views import index, adega, adicionarVinho


urlpatterns = [
    path('', index, name='index'),
    path('adega/', adega, name='adega'),
    path('adicionarVinho/', adicionarVinho, name='adicionarVinho'),
]

wine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

from stdimage.models import StdImageField


class Base(models.Model):
    criado = models.DateField('data de Criação', auto_now_add=True)
    modificado = models.DateField('data de Atualização', auto_now_add=True)
    ativo = models.BooleanField('ativo?', default=True)

    class Meta:
        abstract = True


class Vinho(Base):
    nome = models.CharField('Nome do Vinho',max_length=100)
    cor = models.CharField('Cor',max_length=20,default='Tinto', choices=(('T','Tinto'), ('R', 'Rose'), ('B', 'branco')))
    uva = models.CharField('Uva',max_length=20,default='Cabernet',
                           choices=(('CS', 'Cabernet Sauvignon'),
                                    ('CF', 'Cabernet Franc'),
                                    ('PN', 'Pinot Noir'),
                                    ('ME', 'Merlot'),
                                    ('MA', 'Malbec'),
                                    ('RS', 'Riesling'),
                                    ('TN', 'Tannat'),
                                    ('CH', 'Chardonnay')))
    acucar = models.CharField('Teor de Açucar',max_length=20, default='Seco',
                           choices=(('SC', 'Seco'),
                                    ('DS', 'Demi Sec'),
                                    ('SU', 'Suave'),
                                    ('DO', 'Doce'),
                                    ('NA', 'Nature'),
                                    ('EB', 'Extra Brut'),
                                    ('BR', 'Brut')))
    safra = models.IntegerField('Safra')
    nacionalidade = models.CharField('Nacionalidade',max_length=20, default='Brasil',
                           choices=(('BR', 'Brasil'),
                                    ('AR', 'Argentina'),
                                    ('UR', 'Uruguai'),
                                    ('CH', 'Chile'),
                                    ('PO', 'Portugal'),
                                    ('ES', 'Espanha'),
                                    ('FR', 'França'),
                                    ('IN', 'Inglaterra'),
                                    ('IT', 'Itália'),
                                    ('AL', 'Alemanha'),
                                    ('SU', 'Suiça'),
                                    ('EU', 'Estados Unidos'),
                                    ('AF', 'África do Sul'),
                                    ('AU', 'Austrália')))
    vinicula = models.CharField('Vinícula',max_length=20)
    alcool = models.DecimalField('Teor de Álcool', max_digits=3, decimal_places=1)
    volume = models.IntegerField('Volume')
    reserva = models.CharField('Reserva',max_length=20, default='Reserva',
                           choices=(('RE', 'Reserva'),
                                    ('NR', 'Não Reservado')))
    tonalidade = StdImageField('Tonalidade', upload_to='tonalidade', variations={'thumb': (124,124)})
    img_rotulo = StdImageField('Rótulo', upload_to='produto', variations={'thumb': (124,124)})
    img_garrafa = StdImageField('Garrafa', upload_to='garrafa', variations={'thumb': (256,256)})
    descricao = models.TextField('Descrição',blank=True, null=True)
    preco = models.DecimalField('Preço', max_digits=8, decimal_places=2)
    promocao = models.DecimalField('Promoção', max_digits=8, decimal_places=2)
    estoque = models.IntegerField('Estoque')
    avaliacao = models.IntegerField('Avaliação')
    num_avaliacoes = models.IntegerField('Número de avaliações')
    destaque = models.BooleanField('Destaque', default=False)

    class Meta:
        db_table = 'vinho'

    def __str__(self):
        return self.nome

core/forms.py
from django import forms


class VinhoForm(forms.Form):
    nome = forms.CharField(label='Nome', max_length=100)
    cor = forms.CharField(label='Cor', max_length=20)
    uva = forms.CharField(label='Uva', max_length=20)
    acucar = forms.CharField(label='Teor de Açucar', max_length=20)
    safra = forms.IntegerField(label='Safra')
    nacionalidade = forms.CharField(label='Nacionalidade', max_length=20)
    vinicula = forms.CharField(label='Vinícula', max_length=20)
    alcool = forms.DecimalField(label='Teor de Álcool', max_digits=3, decimal_places=1)
    volume = forms.IntegerField(label='Volume')
    reserva = forms.BooleanField(label='Reserva')
    tonalidade = forms.ImageField(label='Tonalidade', upload_to='produtos', variations={'thumb': (124, 124)})
    img_rotulo = forms.ImageField(label='Rótulo', upload_to='produtos', variations={'thumb': (124, 124)})
    img_garrafa = forms.ImageField(label='Garrafa', upload_to='produtos', variations={'thumb': (256, 256)})
    descricao = forms.CharField(label='descrição', widget=forms.Textarea())
    preco = forms.DecimalField(label='Preço', max_digits=8, decimal_places=2)
    promocao = forms.DecimalField(label='Promoção', max_digits=8, decimal_places=2)
    estoque = forms.IntegerField(label='Estoque')
    avaliacao = forms.IntegerField(label='Avaliação')
    num_avaliacoes = forms.IntegerField(label='Número de avaliações')
    destaque = forms.BooleanField(label='Destaque',initial=False)

core/views.py
from django.shortcuts import render
from core.models import Vinho

def index(request):
    return render(request,'index.html')


def adega(request):
    vinho = Vinho.objects.all()
    dados = {'vinhos': vinho}
    print(vinho)
    return render(request, 'adega.html', dados)


def adicionarVinho(request):
    return render(request,'adicionarVinho.html')

core/templates/adega.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Adega</title>
    {% bootstrap_css %}
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1>adega.html....</h1>
        <hr>
    </div>
    {% for vinho in vinhos %}
    <div class="container">
        <fieldset class="form-group">
            <legend>Vinho</legend>
                <label>Nome  : </label>
                <input type="text" value="{{ vinho.nome }}"><br>
                <label>Cor: </label>
                <input type="text" value="{{ vinho.get_cor_display }}"><br>
                <label>Uva: </label>
                <input type="text" value="{{ vinho.get_uva_display }}"><br>
                <label>Açucar: </label>
                <input type="text" value="{{ vinho.get_acucar_display }}"><br>
        </fieldset><br>
        <fieldset>
            <legend>Origem</legend>
                <label>Vinícula: </label>
                <input type="text" value="{{ vinho.vinicula }}"><br>
                <label>Safra: </label>
                <input type="number" value="{{ vinho.safra }}"><br>
                <label>Nacionalidade: </label>
                <input type="text" value="{{ vinho.get_nacionalidade_display }}"><br>
                <label>Reserva: </label>
                <input type="text" value="{{ vinho.get_reserva_display }}"><br>
        </fieldset><br>
        <fieldset>
            <legend>Informações</legend>
                <label>Álcool: </label>
                <input type="text" value="{{ vinho.alcool }}"><br>
                <label>Volume: </label>
                <input type="text" value="{{ vinho.volume }}"><br>
        </fieldset><br>
        <fieldset>
            <legend>Comercial</legend>
                <label>Preço: </label>
                <input type="text" value="{{ vinho.preco }}"><br>
                <label>Promoção: </label>
                <input type="text" value="{{ vinho.promocao }}"><br>
                <label>Estoque: </label>
                <input type="number" value="{{ vinho.estoque }}"><br>
                <label>Avaliação: </label>
                <input type="number" value="{{ vinho.avaliacao }}"><br>
                <label>Número de avaliações: </label>
                <input type="number" value="{{ vinho.num_avaliacoes }}"><br>
        </fieldset><br>
        <fieldset>
            <legend>Imagens</legend>
                <label>Imagem da tonalidade: </label><br>
                <img src="{{ vinho.tonalidade.thumb.url }}" ><br>
                <label>Imagem da rótulo: </label><br>
                <img src="{{ vinho.img_rotulo.thumb.url }}" ><br>
                <label>Imagem da garrafa: </label><br>
                <img src="{{ vinho.img_garrafa.thumb.url }}" ><br>
        </fieldset><br>
        <fieldset>
            <legend>Descrição</legend>
                <label>Descrição: </label>
                <input type="text" value="{{ vinho.descricao }}"><br>
                <label>Destaque: </label>
                <input type="text" value="{{ vinho.destaque }}"><br>
                <label>Ativo: </label>
                 <input type="text" value="{{ vinho.ativo }}"><br>
        </fieldset><br>
        <hr>
    </div>
    {% endfor%}

{% bootstrap_javascript jquery='full' %}
</body>
</html>

core/templates/adicionarVinho.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AdicionarVinho</title>
</head>
<body>
  <h1>adicionarVinho.html....</h1>
</body>
</html>

core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
  <h1>index.html....</h1>
</body>
</html>